# ===============================
# SQL SERVER CONFIG
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GameStore;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=PanzerTank4so9
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# DISABLE data.sql & schema.sql
# ===============================
spring.sql.init.mode=never
spring.messages.basename=layout
spring.messages.encoding=UTF-8
# ===============================
# VNPAY CONFIG
# ===============================
vnpay.tmnCode=9W7RA43B
vnpay.hashSecret=URT28V95VFE2V08YHULZ2J668LIFGXV6
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/payment/vnpay-return
